In [1]:
import numpy
i = numpy.array([10, 20, 30, 40, 50])
print(i)

[10 20 30 40 50]


In [2]:
import numpy as np
i = np.array([10, 20, 30, 40, 50])
print(i)

[10 20 30 40 50]


In [3]:
 import numpy as np
print(np.__version__)

1.19.2


In [4]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60])
print(i)
print(type(i))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
i = np.array((10, 20, 30, 40, 50, 60))
print(i)

[10 20 30 40 50 60]


In [6]:
import numpy as np
i = np.array(10)
print(i)


10


In [7]:
import numpy as np
i = np.array([10, 20, 30, 40, 50])
print(i)


[10 20 30 40 50]


In [8]:
import numpy as np
i = np.array([
[10, 20, 30],
[40, 50, 60]
])
print(i)


[[10 20 30]
 [40 50 60]]


In [9]:
import numpy as np
i = np.array([
[[10, 20, 30], [40, 50, 60]],
[[11, 22, 33], [44, 55, 66]]
])
print(i)


[[[10 20 30]
  [40 50 60]]

 [[11 22 33]
  [44 55 66]]]


In [10]:
import numpy as np
i = np.array(10)
j = np.array([10, 20, 30, 40, 50])
k = np.array([[11, 22, 33], [44, 55, 66]])
m = np.array([[[10, 20, 30], [40, 50, 60]], [[10, 20, 30], [40, 50,
60]]])
print(i.ndim)
print(j.ndim)
print(k.ndim)
print(m.ndim)

0
1
2
3


In [11]:
import numpy as np
i = np.array([10, 20, 30, 40], ndmin=5)
print(i)
print(i.ndim)

[[[[[10 20 30 40]]]]]
5
